train: 
  batch_size: 128
  early_stop_mode: max
  early_stop_patience: 20
  epochs: 3 # 1000
  device: cpu
  optimizer: adam
  learning_rate: 0.001
  weight_decay: 0
  num_neg: 1   # number of negative items to be sampled
  seed: 2023  # random seed, usually 42 is a magic number

model: 
  embed_dim: 64
  loss_fn: 'bce'

eval:
  batch_size: 128 # 2048
  cutoff: [20, 10]
  val_metrics: [ndcg, recall]
  test_metrics: [ndcg, recall]
  topk: 50 # Max len of user hist to reduce complexity
  save_path: './saved/'
